-- migration: create refresh_tokens table for secure rotation
-- generated by secure/auth-rotation-fix

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGSERIAL PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  token_hash VARCHAR(512) NOT NULL,
  jti VARCHAR(128),
  dispositivo VARCHAR(255),
  ip_origem INET,
  user_agent TEXT,
  criado_em TIMESTAMPTZ DEFAULT NOW(),
  expira_em TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ NULL,
  rotacionado_em TIMESTAMPTZ NULL,
  revogado BOOLEAN DEFAULT false,
  CONSTRAINT refresh_tokens_token_hash_unique UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS refresh_tokens_usuario_id_idx ON refresh_tokens (usuario_id);
CREATE INDEX IF NOT EXISTS refresh_tokens_token_hash_idx ON refresh_tokens (token_hash);
