-- migration: add family_id to refresh_tokens for reuse detection
-- generated by secure/auth-hardening

ALTER TABLE refresh_tokens 
ADD COLUMN IF NOT EXISTS family_id UUID,
ADD COLUMN IF NOT EXISTS revoked_reason TEXT;

-- For existing rows, assign a random UUID to family_id so we don't break them, 
-- or we can just leave it to be updated. Since family_id shouldn't be null going forward,
-- we initialize existing rows.
UPDATE refresh_tokens SET family_id = gen_random_uuid() WHERE family_id IS NULL;

-- Now make it NOT NULL
ALTER TABLE refresh_tokens ALTER COLUMN family_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS refresh_tokens_family_id_idx ON refresh_tokens (family_id);
